### ISSUE TITLE
File listing and indexes too large

### ISSUE THREAD

**Issue by mariusvniekerk** [regro/libcfgraph#10]
cc @CJ-Wright 

remote: warning: File .file_listing.json is 73.29 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB        
remote: warning: File .indexed_files is 68.79 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB

**Comment by jaimergp** [comment]
Aaand we are over 100 MB now for `file_listing.json`, which fails the push. [See logs](https://app.circleci.com/pipelines/github/regro/libcfgraph/39065/workflows/73ab3a89-5667-4bc0-9144-88efeb7b4c3c/jobs/52925).

Possible solutions (in `libcflib` I guess?):

- Gzip the thing. I tried locally and goes all the way down to 6MB. However this will be handled nicely by `git` deltas.
- Shard the thing. Divide in two or three JSONs, and then have consumers fetch everything.

Who is using these files?

- A github [search](https://github.com/search?q=org%3Aconda-forge%20file_listing.json&type=code) for `file_listing.json` shows two: `by-the-numbers` and `artifact-validation`.
- Searching for `indexed_files` shows [nothing](https://github.com/search?q=org%3Aconda-forge+indexed_files&type=code).

In `regro`:

- [conda-forge-feedstock-check-solvable](                "/master/.file_listing.json")


We could also look into flattening the repo... I am cloning it to see `git sizer` reports, but it's taking a while :D

**Comment by beckermr** [comment]
I fixed the file listings for now. It appears we'll want to move to the ghcr stuff anyways.
